### ISSUE TITLE
关于功能几点建议

### ISSUE THREAD

**Issue by juestchaos** [bluesky139/LTweaks#1]
1.系统以图搜图，能否支持自定义搜索引擎，每次都要翻很不方便
2.既然京东可以支持价格比较，淘宝应该也可以求支持

**Comment by bluesky139** [comment]
都可以加，但优先级会很低，先 pending 起吧。

**Comment by juestchaos** [comment]
作者回复好及时，赞

**Comment by bluesky139** [comment]
1. 现在以图搜图添加了 TinEye 和 IQDB，不想再添加自定义。如果你还知道什么好的搜索引擎我可以考虑加进去。
2. 淘宝确实可以支持，但跟京东或苏宁不一样，淘宝在商品 ID 不变的情况下商品是可变的，而且一个商品 ID 下面可以有多个商品，可参考性太低，不想去支持。
