### ISSUE TITLE
“L工具箱已停止运行”、Youtube清晰度设定无效，以及一点语言建议

### ISSUE THREAD

**Issue by Gokou-Ruri** [bluesky139/LTweaks#11]
Android 7.1.2（rr5.8.3） 系统dp值：600（Chrome界面为平板模式） L工具箱版本：1.14.1
选中文本后，在浮动菜单里里选择“BILIBILI”，会弹出“L工具箱已停止运行”。
长按选中文本后在浮动菜单里选择“隐身搜索”，会弹出“L工具箱已停止运行”。但依然能够打开隐身页面。
或者在Chrome内浏览任意网页时从菜单里选择“Open in incognito”，也会弹出“L工具箱已停止运行”。但依然能够打开隐身页面。
顺带问一下为啥长按文本的浮动菜单里的“隐身搜索”是中文，而Chrome菜单里的“以隐身模式打开”却是英文“Open in incognito”呢？还有选中文本的浮动菜单里把“BILIBILI”换成“哔哩哔哩”更好些。
感觉统一一些比较美观吧(我的系统语言是简中)。
另外如题，youtube清晰度设定选择任何一项都没有效果，比如720p、1080p(视频是有这两个清晰度的，可以手动切换，但在L工具箱里设定清晰度无效。)。youtube版本：12.39.60 arm64

**Comment by bluesky139** [comment]
感谢反馈。
7.0 上有些功能还有问题，我正在修复。
翻译是有些地方没有，我平时在用英文系统，有时没注意。
Youtube 清晰度的问题我最近使用的时候也发现了，可能新版本有什么变化，先修复了 7.0 的问题再来看。

**Comment by Gokou-Ruri** [comment]
@bluesky139 感谢回复！另外突然想到个建议：youtube的客户端在某些机型上点击全屏播放时，无法正确自动旋转屏幕(全屏播放模式下依然是竖屏，上下黑色，中间显示视频画面)。请问能不能顺带做一下全屏播放时强制旋转屏幕的功能呢？
（我现在的解决办法是设定规则，当youtube运行时，屏幕锁定为横屏，全屏后就依然是横屏……）

**Comment by bluesky139** [comment]
我个人没有遇到 Youtube 的全屏问题，所以也不好调试，也许你应该向 Google 反馈，虽然被修复的几率很低:confused:。

**Comment by Gokou-Ruri** [comment]
两台机都这样，其中一台以前能旋转，现在不转了。
我也是感觉向google反馈很难得到修复，所以没提交。但是有人说提交过了，等google修复，然而没动静……说真的youtube客户端使用体验比一些国内视频客户端还烂。也就画质好，广告可以3秒跳。

**Comment by bluesky139** [comment]
Fixed crash in f912acc8cb7c83e259baa2312cf64cd0e4b9880b.
Fixed Youtube in 115d399c6becbfc093d4ad6e67eb1d76c491ca36.

**Comment by bluesky139** [comment]
Translation is updated in 559aad4cd900c64842e26048f9250ec8055bf0a0.
