### ISSUE TITLE
新功能建议：chrome浏览百毒盘页面时自动跳转到via打开

### ISSUE THREAD

**Issue by Gokou-Ruri** [bluesky139/LTweaks#12]
例如：pan.baidu.com/s/1hqmvH7e
当chrome访问毒盘下载页面时，自动跳转到via浏览器打开该页面。

因为via浏览器有个js可以直接显示毒盘的下载按钮，而且via可以直接调用ADM下载器下载。（因为chrome的同步功能具备很强的用户黏性，所以我平时很少用via，默认浏览器chrome。）

**Comment by bluesky139** [comment]
我觉得这个可以做成通用的，选择其它支持此链接的应用打开链接。

**Comment by Gokou-Ruri** [comment]
那就更好了！我是担心现在要兼容Android 7，计划太多顾不上。

**Comment by bluesky139** [comment]
这个功能会 pending 起放到一边，等其它所有修复问题解决了再来。
这是个人开源的一个小项目，空闲时间搞一搞，确实会有顾不上的时候，有空就做，不卡时间，不赶进度。

7.0 的兼容问题比我想像的麻烦，Xposed 本身对 ROM 还有不完全适配的情况，昨天提了一个 [issue](https://github.com/rovo89/XposedBridge/issues/206).

**Comment by bluesky139** [comment]
Added in 0f6532b8de449a530194766815c5b3f99af2ab87.
