### ISSUE TITLE
7.1.1上的bug

### ISSUE THREAD

**Issue by chenyue404** [bluesky139/LTweaks#13]
一加3T，7.1.1，Xposed 88.1
如果把“系统/工具”里面的“显示所有菜单项”打开的话，联想日历的黄历，京东金融的京东小金库，点击就crash。

**Comment by Gokou-Ruri** [comment]
目前对原生Android 7都还处于适配中，楼主居然是国产ui。个人以为这个软件并不适合国产ui使用吧，主要是各种国产ui对Android魔改严重，不符合标准，很难兼容。

**Comment by bluesky139** [comment]
我试了下联想日历，没有问题。我没有京东金融，无法测试。
可以的话请在电脑上取下完整log.

**Comment by chenyue404** [comment]
现在又没法复现了，蛋疼……
