### ISSUE TITLE
清除play数据之后可以了。。

### ISSUE THREAD

**Issue by uoox** [bluesky139/LTweaks#14]
另外，希望增加一个Chrome和WebView的功能：
自定义「选中文字后长按的悬浮菜单」，我想把「翻译」放在「复制」后面，而把其他的（如分享，全选）去掉或者放在三个点里面，这样只要点一次就能翻译了，而且「分享」我用的很少，至于「网页搜索」，在选中时，在Chrome，最下面会自动出现一个临时的tab，内置浏览器还是需要的，所以我觉得能修改这个菜单挺实用的。

**Comment by bluesky139** [comment]
"View in coolapk" 偶尔有失效的情况，我也遇到过，但我自己也没法重现，几率太低就不管了。

浮动菜单的屏蔽和排序我以前也考虑过，我也觉得实用，我会尝试把它加上。

**Comment by bulabulabula1996** [comment]
厉害了老铁  想法一样   有些基本用不到的隐藏了更美观

**Comment by bluesky139** [comment]
Added in 24d3d51a8688d7781511c322fe262bcf0beb90eb.
