### ISSUE TITLE
htc u11 无法进入设置中的指纹识别器

### ISSUE THREAD

**Issue by lm789632** [bluesky139/LTweaks#15]
仅仅只是激活，不进行任何设置就会这样，取消激活就好了

**Comment by bluesky139** [comment]
不清楚你说的无法进入是如何无法进入，请详细描述。
这种设备特有的问题不好调试。
你可以先在电脑上取完整 log 让我看一下看有没有什么有用的信息（从开机到有问题的地方）。

**Comment by lm789632** [comment]
[正常打开指纹识别器会进入图形解锁界面，但是激活 LTweaks 后点击指纹识别器，设置界面会卡住大约3s后变纯黑，但状态栏是正常的，直接按返回无法退出此界面，可以按多任务键或主页键退出。
我用 adb logcat 获取的日志，不知道有没有用
https://drive.google.com/file/d/0B4_Mb3lqksaVeFczWXR2NFNSWTg/view?usp=sharing

**Comment by bluesky139** [comment]
这个 log 不全，没有开机过程中的 log，你先关机，然后开机，在开机的过程中连数据线，那个时候已经可以取到 log 了（会有 Xposed 加载各个模块的 log）。

**Comment by lm789632** [comment]
应该是我取日志的时候加过滤设置了，这次啥过滤都没加，直接 adb logcat ，还取了两次。谢谢^_^
1：https://drive.google.com/file/d/0B4_Mb3lqksaVLUFWaXphSFBWOGM/view?usp=sharing
2：https://drive.google.com/file/d/0B4_Mb3lqksaVUnJla2lYRjJYNDA/view?usp=sharing

**Comment by lm789632** [comment]
@bluesky139

**Comment by bluesky139** [comment]
Log 仍然不全，没有最初加载模块的那部分。
但是我猜测了最可能出问题的地方，我打了个临时版本，你试一下：
[https://drive.google.com/open?id=0B27qXp7hMrkjN3ktcF8wRzBxY0E](https://drive.google.com/open?id=0B27qXp7hMrkjN3ktcF8wRzBxY0E)

**Comment by lm789632** [comment]
我卸载旧版本，重新安装这个版本，还是同样的问题。我是运行 adb logcat 命令开机的，按理说 log应该很全啊，我再试试取一次

**Comment by bluesky139** [comment]
你再取一次，同时到 Xposed Installer 取那里面的日志出来。

**Comment by lm789632** [comment]
我又取了两遍， Xposed Installer 里的日志也保存出来了。
https://drive.google.com/open?id=0B4_Mb3lqksaVWGU5dnNDOFZ3aGs
麻烦你了。 @bluesky139

**Comment by bluesky139** [comment]
从 log 中看不出什么有用的东西，现在我觉得只有想办法缩小问题范围，我打了4个包，你依次试一下给我结果。
[https://drive.google.com/open?id=0B27qXp7hMrkjLUxMV2xNMjF5b3M](https://drive.google.com/open?id=0B27qXp7hMrkjLUxMV2xNMjF5b3M)

**Comment by lm789632** [comment]
我试了下，使用第一个和第三个问题解决，第二个和第四个问题依旧，所以说问题出在对 系统设置 的修改上？@bluesky139

**Comment by bluesky139** [comment]
我修改了一下 preferences 的读取方法，请再试一下。
[https://drive.google.com/open?id=0B27qXp7hMrkjTjFiUlZLd2p3RUk](https://drive.google.com/open?id=0B27qXp7hMrkjTjFiUlZLd2p3RUk)

**Comment by lm789632** [comment]
用了这个版本问题不再发生此问题了。这就是说问题解决了吧？好开心。^_^

**Comment by bluesky139** [comment]
对，Fixed in 74ab59b5263123d0d1fddf2166b54ab35c5b1371.
非常感谢 @lm789632 有耐心的多次来回调试。
