### ISSUE TITLE
功能添加

### ISSUE THREAD

**Issue by bulabulabula1996** [bluesky139/LTweaks#19]
希望能添加 隐藏选中文本后的浮空菜单选项('◇'｀)

**Comment by bluesky139** [comment]
想不到任何使用场景。

**Comment by bulabulabula1996** [comment]
就是有些  选中文本后的浮空菜单 里的选项  基本上使用不到  所以希望出一个能隐藏掉 很少使用到的选项  就和隐藏用不到的分享菜单里的分享差不多的那种('◇'｀)

**Comment by bulabulabula1996** [comment]
就是有些‘’选中文本后的浮空菜单‘’里的‘’选项‘’，有些是使用不到的，或者很少使用的。比方说有个应用《搜索Lite》 安装之后长按选择文本 ，会多出一个‘’搜索Lite‘’的选项，但是这个选项实用性太小。所以希望出一个能隐藏掉很少使用到的选项的功能。就和隐藏分享菜单里那些很少使用到的分享差不多的那种功能（'◇' `）

**Comment by bluesky139** [comment]
我理解错了，这个功能已经添加了，https://github.com/bluesky139/LTweaks/commit/24d3d51a8688d7781511c322fe262bcf0beb90eb.

#14

**Comment by bulabulabula1996** [comment]
✧٩(ˊωˋ*)و✧

**Comment by bulabulabula1996** [comment]
管理浮空菜单 。 设置之后重启。。。发现没有效果。。。。 就我一个人吗。。。。 在知乎和酷安里都测试了 无效_(:з」∠)_ 安卓版本7.1.2  rr  5.8.5 20171119 最终版   手机  红米Note3pro

**Comment by bulabulabula1996** [comment]
不过在浏览器里似乎有效

**Comment by bluesky139** [comment]
酷安有反 Xposed 功能，在设置里面关掉就对了。
知乎估计也有类似的功能吧，我没有使用不清楚。

**Comment by bulabulabula1996** [comment]
好的
