### ISSUE TITLE
可以增加修改折叠同一应用通知的限制吗

### ISSUE THREAD

**Issue by pototar** [bluesky139/LTweaks#20]
目前需要三条通知以上才会折叠，但是那会已经很挤了。。
能改成一条以上就折叠吗

**Comment by bluesky139** [comment]
我通知少没注意过，能截个图说明下吗。顺便问下系统版本多少。

**Comment by pototar** [comment]
![1](https://user-images.githubusercontent.com/9803841/33657057-12c1bf22-dab3-11e7-82dc-cab73933ffe3.png)
![screenshot_20171206-181940](https://user-images.githubusercontent.com/9803841/33657071-1add271e-dab3-11e7-884b-a75c2b205203.png)
大概就这样
AOSP 7.1.2

**Comment by bluesky139** [comment]
看[这里](https://github.com/aosp-mirror/platform_frameworks_base/blob/eb72a7f4579b61031b4cb66afa43a82f823430f5/packages/ExtServices/src/android/ext/services/notification/Ranker.java#L44)确实是要达到4个后才折叠，然后不好 hook.

**Comment by pototar** [comment]
计划失败了😂😂
