### ISSUE TITLE
京东不能查看历史价格了

### ISSUE THREAD

**Issue by lastonesky** [bluesky139/LTweaks#22]
以前的版本都好好的，最近版本复制链接之后没有share提示了

**Comment by bluesky139** [comment]
我重新测试了一下最近发布的 1.16.0 版本，一切正常。
京东那一栏里面的“使用系统分享来分享商品”是否勾上？
另外，在“系统/工具” -> “系统分享” -> “复制后分享”有同样的功能，勾上试试。这个功能是针对所有应用，你也可以试下在其它应用里复制看有没有分享提示。

**Comment by lastonesky** [comment]
抱歉，重新安装了模块之后，现在又正常了。
