### ISSUE TITLE
请求支持酷安V8

### ISSUE THREAD

**Issue by naloder** [bluesky139/LTweaks#25]
酷安V8进入公测beta了，虽然好看，但是还是怀念当初的MD抽屉样式，可以考虑支持吗？或者能适配官方的共存v7也行。。_(:з」∠)_

**Comment by bluesky139** [comment]
在未进入正式版以前的版本通常会有各种改动，支持起来比较繁琐，我会在正式版发布的时候再进行支持。

**Comment by naloder** [comment]
@bluesky139那可以先做个支持共存版的吗。要的话我可以提供_(:з」∠)_

**Comment by bluesky139** [comment]
共存的 v7 只是改了个包名，已适配 cdc062e7232285c02c7a7ff58966b39a7863b59b.

**Comment by naloder** [comment]
V8也出现了抽屉侧栏，但是有加号而且小飞机发送键还在原位置，能否暂时屏蔽

**Comment by bluesky139** [comment]
处理了一下，在有共存 v7 的情况下，不对原包进行 hook. 03461a937f2f6acf3e7f11d0ab84a4d654baf1cb

**Comment by naloder** [comment]
正式版发布了_(:з」∠)_(ps：最近版本L工具箱会有啥新特性了吗。)

**Comment by bluesky139** [comment]
好的，我会在过年这段时间跟进支持。
每次发新版本我都把新特性列出来了的，至于后续会有什么我也不知道，有好的需求就慢慢做，不刻意添加用不到的功能。

**Comment by bluesky139** [comment]
开始支持 v8.1，不再支持 v7. da7ef583b607e8c118a5e4226a64ef1a742e6586
