### ISSUE TITLE
我又来提建议啦

### ISSUE THREAD

**Issue by uoox** [bluesky139/LTweaks#26]
希望可以把google play服务的 location report enabler和assistant enabler合并进来欧，前者可以让Google搜索的feed和Google健康的位置记录生效，或者可以在英文系统开启语音

**Comment by bluesky139** [comment]
我没有研究过这两个功能，不知道要满足哪些条件才能开启，我觉得你可以就用目前的方式来开启。

**Comment by uoox** [comment]
嗯嗯，前者是通过替换运营商代号，后者也许是修改手机信息为pixel？不过这个issue可以close啦，我也觉得可能并不是那么的重要
