### ISSUE TITLE
Youtube部分建议

### ISSUE THREAD

**Issue by naloder** [bluesky139/LTweaks#27]
希望能把一些第三方添加进修改版youtube的功能做到模块里面，这样就能用官方版了_(:з」∠)_：广告屏蔽（非刚需），屏幕左边上下拖动调整亮度，右边调整音量，屏幕上拖动快进视频，后台播放啥的_(:з」∠)_

**Comment by bluesky139** [comment]
这几个功能我自身也考虑过，先 pending 起吧。
你在哪个修改版上看到的这些功能？

**Comment by naloder** [comment]
OG youtube和IYTBP这两个修改版本（前者支持下载，功能好用，但是已经停更而且无法解析下载:joy:后者版本比较新支持三种安装方法:root，免root，magisk，而且做的界面比较干净，去了大部分广告，还加入了开启强制vc9）

**Comment by Gokou-Ruri** [comment]
@naloder vc9？是指vp9吧？vp9比avc都差得多，为什么要强制vp9？而且相对比较老款的机型一般都不支持vp9硬解码。
另外，期待av1吧，基于vp10开发的，据现有实际测试效果在低码率下已经大幅超越avc和hevc。

**Comment by naloder** [comment]
@Gokou-Ruri 那期待集成喽ԅ(¯﹃¯ԅ)

**Comment by fanghuan27** [comment]
这几个功能幸运破解器上的有大佬在跟进 去广告就扯了 做adaway那哥们也不更新了 要去广告目前只能修改版

**Comment by bluesky139** [comment]
我个人觉得 YouTube 上的广告都还好，至少我都能接受，配合我的广告 id，越来越精准了😁

其它功能，我目前只能说我 YouTube 本身用得少，都没什么动力去做，而且 YouTube 那个代码混淆很恼火😫

**Comment by fanghuan27** [comment]
以前的广告感觉都很好不想跳 但是最近这一年开始香港节点的广告制作有些low啊 还老是费列罗麦当劳啥的 台湾的广告也low但是还稍好一点点 最近试着换到俄罗斯质量又很高
