### ISSUE TITLE
not working !!!

### ISSUE THREAD

**Issue by repoman728** [bluesky139/LTweaks#29]
It does nothing , install on Huawei mate 9 with xposed running and nothing happend
switched on - add menu ... vien in coolapk and nothing , 
wayback machine  on - norhing too go top bar -nothing !
and yes i rebooted phone
reg

**Comment by bluesky139** [comment]
It should be a device specific problem, can you reboot once and get full log for me?

**Comment by repoman728** [comment]
how to do or where i can find the log  in your app save log shows error

**Comment by bluesky139** [comment]
It's better to get log from PC, the log from app is not complete.

**Comment by repoman728** [comment]
remind me how to do it cause I haven't done that yet , please

**Comment by bluesky139** [comment]
There's log in XposedInstaller, you can get it from there. I think I can see this log first.

**Comment by repoman728** [comment]
ok  but i have to find where is error because log is empty

**Comment by repoman728** [comment]
[Log_2018-02-09_14-53-32.txt](https://github.com/bluesky139/LTweaks/files/1710881/Log_2018-02-09_14-53-32.txt)
is this ok

**Comment by bluesky139** [comment]
It looks like this log is not from XposedInstaller.
And from this log, I only know you set Youtube quality, have you try other methods, such as "Remove Youtube bottom bar"?

**Comment by repoman728** [comment]
HI 
 I have tried  that method for yutube but it didn't work either . 
I also tried for steam app but also no success , maybe it is not for huawei 
reg

**Comment by bluesky139** [comment]
I don't have that device to test, so the only way is give me more log.

**Comment by repoman728** [comment]
which logs and how to get them

**Comment by bluesky139** [comment]
Refer: https://developer.android.com/studio/command-line/logcat.html

**Comment by repoman728** [comment]
coulfd you please just write commands and I will paste them, thanks

**Comment by bluesky139** [comment]
A simple command is: adb logcat > a.txt
But you can't use it directly, you need to install Android sdk and driver for your phone.

This is out of my support, it's very simple to get log from phone, more details on Google, and there's difference on each device, such as driver installation. 
For most of people, it's better to use some tool to get it.

**Comment by bluesky139** [comment]
I don't know why the log which you previous provided is not complete, and it's not look like it come from XposedInstaller.
