### ISSUE TITLE
Google Photos v2.17.0 drawer内布局错乱

### ISSUE THREAD

**Issue by mikelei8291** [bluesky139/LTweaks#3]
![screenshot_20170623-010307_mosaic_1_3_20_mosaic_1_5_0](https://user-images.githubusercontent.com/9620335/27447475-aff0fc00-57b3-11e7-905d-d56a9aa78228.png)

**Comment by bluesky139** [comment]
Fixed in bb487724185e1d24cab116dc0e098593c820895b.
