### ISSUE TITLE
微信drawer menu的改进建议

### ISSUE THREAD

**Issue by ZBTJ** [bluesky139/LTweaks#31]
希望微信的drawer menu可以进一步将常用功能整合进二级菜单 比如在“发现”下可以列出常用的朋友圈 扫码 小程序 在“我”下可以列出钱包 设置 等功能。现在的drawer menu有些强行MD的感觉 实用性不强。谢谢开发者！

**Comment by bluesky139** [comment]
现在这个样子是有一定原因的：
1. 本身这个功能的目的就是简单的把底栏去掉，不做过多的事。
2. 要把其它功能加进来又要时不时进行维护，这个功能从最初实现后到现在未进行过任何更新，仍然兼容最新的微信。现在的菜单采用的是自适应的，比如哪天底栏的某个按钮换成另一个了，或者变成5个按钮了，也能适配。
3. 二级菜单点两次，跟切换页后再点一次，我觉得没有本质区别。
我希望保持简洁，望理解。

**Comment by ZBTJ** [comment]
原来如此 感谢开发者！
