### ISSUE TITLE
Autorun Stopper Not Work In Marshmallow

### ISSUE THREAD

**Issue by jerzzey** [bluesky139/LTweaks#32]
In my phone Luna G it seems the Prevent App From Running Or Autorun Stopper it seems not work can you fix it? Because after apply some app and few minutes later my phone became heat again and if i opening auto task manager its seems the app who i list prevent from auto running its show in task killer and clean memory, please fix it

Thx and best regards

Sorry for my bad english languange

**Comment by bluesky139** [comment]
Prevent running in this module is not precisely prevent apps running, it just does some slight works to reduce running possibility, you can see instruction by clicking "info" icon on each prevent function.

You can use "prevent running" module (another Xposed module has this name) to get what you want.

**Comment by jerzzey** [comment]
But i like your hardwork if you can please add this tool i appreciate it, thx

**Comment by bluesky139** [comment]
The function of prevent running in my module is to assist the original prevent running module, this is the design. 
And, they have done the perfect module, why I have to recreate another one.
