### ISSUE TITLE
求更新 新版本的G+和photos去不掉了 

### ISSUE THREAD

**Issue by fanghuan27** [bluesky139/LTweaks#33]
照片底下一坨白条 G+直接去不掉了只能装回旧版本

**Comment by bluesky139** [comment]
感谢提醒，我会在近期看看。

**Comment by fanghuan27** [comment]
ty 感谢付出！

**Comment by bluesky139** [comment]
G+ 修复了 ab9d013587eea726453ffad07a08c917172aa1c9.
Photos 没有发现你说的一它白条呢？我装了 v3.15 跟以前是一样的。

**Comment by fanghuan27** [comment]
![screenshot_20180301-180901](https://user-images.githubusercontent.com/1284794/36839101-fe86b0a6-1d7b-11e8-81be-70b87f5a2863.png)
![screenshot_20180301-180919](https://user-images.githubusercontent.com/1284794/36839112-09c82814-1d7c-11e8-80ba-19600f325264.png)
这样子

**Comment by bluesky139** [comment]
Photos 去掉白条了 c3d418d8a95222299d5cefdea8bbc5af75111701.

**Comment by fanghuan27** [comment]
报告 固定分辨率在youtube13.09.57版本上失败了

**Comment by bluesky139** [comment]
固定分辨率是失效了，这个功能实现起来有点麻烦，我会尝试修复。

**Comment by fanghuan27** [comment]
OK

**Comment by fanghuan27** [comment]
报告 我这里youtube更新了13.14.55版本还是会经常不能固定分辨率 似乎在刚进去首页点击的视频可以 但是收藏里的不行 播放列表自动播放下一个也会失效 是因为我更新的是arm64版本的原因吗还是说是本身不稳定？

**Comment by bluesky139** [comment]
应该跟 arm64 没有关系，我只测试过首页和外部链接进入的情况，收藏和自动播放下一个没有试过，我后面试试。
