### ISSUE TITLE
Google play books does not remove bottom bar 

### ISSUE THREAD

**Issue by oops-unify-yo** [bluesky139/LTweaks#34]
Version: 4.0.47.184185130 (newest)

之前的版本一个个试过去了，都不行…
现在在找没有底栏的旧版…

**Comment by bluesky139** [comment]
这个是在 v3.16 上进行适配的，确实在 v4.0 上不兼容的，我会在后续进行修复。

**Comment by oops-unify-yo** [comment]
感谢～但我在3.16上测试时仍无法正常去除底栏
此外Google搜索（开启feed后）也无法去除底栏
xposed：89.2 systemless，Android 7.1.2

bluesky139 <notifications@github.com> 于 2018年3月11日周日 18:31写道：

**Comment by bluesky139** [comment]
你用最新的 v4.0 的 Google Play Books 测试一下这个 apk，我刚才修复了 9202700a4049d432e9aa5e6d1b2f4df64d20a51b.
[01_4.0_GooglePlayBooks.apk.zip](https://github.com/bluesky139/LTweaks/files/1801003/01_4.0_GooglePlayBooks.apk.zip)

我也看了最新的 v7.21 的 Google 搜索，已经变样了，肯定不兼容以前的适配，他把抽屉菜单直接放到了一个底栏按钮上。我先看看。

**Comment by oops-unify-yo** [comment]
还是无法去除
[book.log](https://github.com/bluesky139/LTweaks/files/1819205/book.log)

**Comment by bluesky139** [comment]
你能把你手机上 Google Play Books 的 apk 给我吗，从 log 的情况来看，相同的代码在你的手机上检测不到底栏，我只能先猜测我们的 apk 可能不同。

**Comment by oops-unify-yo** [comment]
就是 google  play 上的..
[base.zip](https://github.com/bluesky139/LTweaks/files/1821246/base.zip)

**Comment by bluesky139** [comment]
麻烦跑一下这个版本，我打了更多的 log 出来，安装重启后进到主界面就可以了。
[02_MoreLog.zip](https://github.com/bluesky139/LTweaks/files/1821269/02_MoreLog.zip)

**Comment by oops-unify-yo** [comment]
[book.log](https://github.com/bluesky139/LTweaks/files/1821342/book.log)

**Comment by bluesky139** [comment]
跟我的 log 对比了一下，发现似乎你的底栏上只有 3 个按钮？
我的有 4 个：Home, Library, Discover, Shop，你的没有 Discover 对不？
我处理了一下，你试试。
[03_3BottomButtons.zip](https://github.com/bluesky139/LTweaks/files/1821462/03_3BottomButtons.zip)

**Comment by oops-unify-yo** [comment]
对，神奇的灰度测试…
我回去试试

bluesky139 <notifications@github.com> 于 2018年3月17日周六 17:36写道：

**Comment by oops-unify-yo** [comment]
低栏去除了，感谢。还有个不影响使用的小bug，当在首页和书架页面时，它们在侧栏中的图标会无法显示。
![default](https://user-images.githubusercontent.com/25275116/37555773-f8310ff4-2a27-11e8-9027-b584e47f79bb.png)
![default](https://user-images.githubusercontent.com/25275116/37555776-ff1aa708-2a27-11e8-81a1-5af4816090be.png)

**Comment by bluesky139** [comment]
这个小 bug 是已知的，当时去底栏的时候就发现了，然而尝试解决无果就先没管了，不影响使用。
