### ISSUE TITLE
能支持total commander么？

### ISSUE THREAD

**Issue by lshilshi** [bluesky139/LTweaks#35]
APP的详情页的apk folder\data folder……
等快捷指向的文件夹，你说在ES浏览器下测试通过

我安装的total commander（https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander）,已root
打开出现错误，只显示ERROR

请问如何解决？或者加入对total commander的支持，谢谢了！

**Comment by lshilshi** [comment]
看了下xposed框架的log
和 
系统log
没找到有用的出错信息

**Comment by bluesky139** [comment]
不是 ES， 是 Solid Explorer.
我进行了一定的修复 7e0d11cdf9b82c6ddfc117bc34d59e084d35ee01，并不是所有文件浏览器都起使用，至少 Total Commander 也起作用了。

**Comment by lshilshi** [comment]
谢谢！
在下一版本时候再更新？

**Comment by bluesky139** [comment]
一般情况下都是下一个版本更新，我不可能改一个地方就发一个版本，我在考虑要不要把 nightly build 弄起，但似乎没有必要的样子。

前两天在解决其它问题的时候有临时版本，你可以先用[这个](https://github.com/bluesky139/LTweaks/files/1821462/03_3BottomButtons.zip).

**Comment by lshilshi** [comment]
用了，这次没有toast提示error了，但是没反应
看了下log，错误消息是
03-23 22:52:18.802: E/Xposed  (3641):  	at li.lingfeng.ltweaks.utils.ContextUtils.openFolder(ContextUtils.java:377)
03-23 22:52:18.802: E/Xposed  (3641):  	at li.lingfeng.ltweaks.xposed.system.XposedAppInfoGoAppData.menuItemSelected(XposedAppInfoGoAppData.java:47)
03-23 22:52:18.802: E/Xposed  (3641):  	at li.lingfeng.ltweaks.xposed.system.XposedAppInfo$2.beforeHookedMethod(XposedAppInfo.java:54)
03-23 22:52:20.857: E/Xposed  (3641):  	at li.lingfeng.ltweaks.utils.ContextUtils.openFolder(ContextUtils.java:377)
03-23 22:52:20.857: E/Xposed  (3641):  	at li.lingfeng.ltweaks.xposed.system.XposedAppInfoGoAppData.menuItemSelected(XposedAppInfoGoAppData.java:51)
03-23 22:52:20.857: E/Xposed  (3641):  	at li.lingfeng.ltweaks.xposed.system.XposedAppInfo$2.beforeHookedMethod(XposedAppInfo.java:54)

是否需要log的info级别信息？（现在是warn级别）

**Comment by bluesky139** [comment]
麻烦给下这一段的完整 log，这里虽然打出了 stacktrace，但没有看到是什么 exception.  warn 级别就行。

**Comment by lshilshi** [comment]
抱歉，我用的MAT自带的logcat查看，即使调整到verbose级别。相关的log也差不多是上面这些
exposed的log我也看了，也是这些（除了一些加载模块激活的log）

你能说说要如何获取你需要的log吗？

**Comment by bluesky139** [comment]
看看 XposedInstaller 里面的 log 呢。
不行的话就连到电脑上用 adb 看看。

**Comment by lshilshi** [comment]
这是电脑adb看的log

03-27 10:24:08.271 D/OpenGLRenderer( 3610): endAllActiveAnimators on 0x7f6b9a1000 (MenuPopupWindow$MenuDropDownListView) with handle 0x7f51bec760
03-27 10:24:09.874 I/Xposed  ( 3610): Menu Open APK Folder click.
03-27 10:24:09.878 V/Xposed  ( 3610): openFolder /data/app/com.bcedu.exam-1
03-27 10:24:09.883 E/Xposed  ( 3610): android.os.FileUriExposedException: file:///data/app/com.bcedu.exam-1 exposed beyond app through Intent.getData()
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1806)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.net.Uri.checkFileUriExposed(Uri.java:2347)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9030)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8991)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.Activity.startActivityForResult(Activity.java:4229)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.Activity.startActivityForResult(Activity.java:4187)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.Activity.startActivity(Activity.java:4526)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.Activity.startActivity(Activity.java:4494)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at li.lingfeng.ltweaks.utils.ContextUtils.openFolder(ContextUtils.java:377)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at li.lingfeng.ltweaks.xposed.system.XposedAppInfoGoAppData.menuItemSelected(XposedAppInfoGoAppData.java:64)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at li.lingfeng.ltweaks.xposed.system.XposedAppInfo$2.beforeHookedMethod(XposedAppInfo.java:54)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.settings.applications.InstalledAppDetails.onOptionsItemSelected(<Xposed>)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.Fragment.performOptionsItemSelected(Fragment.java:2476)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2182)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:336)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.Activity.onMenuItemSelected(Activity.java:3211)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:93)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:68)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.widget.Toolbar$1.onMenuItemClick(Toolbar.java:193)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1211)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3305)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.widget.AbsListView$4.run(AbsListView.java:4228)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.os.Handler.handleCallback(Handler.java:751)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.os.Looper.loop(Looper.java:154)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at android.app.ActivityThread.main(ActivityThread.java:6236)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at java.lang.reflect.Method.invoke(Native Method)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
03-27 10:24:09.883 E/Xposed  ( 3610): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by bluesky139** [comment]
修复了 def4e20c91d8b8070f10475e333023d059fd9376.
