### ISSUE TITLE
一个小改进

### ISSUE THREAD

**Issue by naloder** [bluesky139/LTweaks#37]
酷安的小飞机图标，就是快捷发表图标仍然会留在界面上，是否可以移动到侧栏或者做到其他地方去

**Comment by bluesky139** [comment]
请截图看一下，我应该移动了的。

**Comment by naloder** [comment]
重启一下正常了。没有实时生效而已。没问题了

**Comment by naloder** [comment]
对了。。改变自定义主题颜色之后侧栏颜色没有实时变化。。这是bug吗

**Comment by bluesky139** [comment]
酷安设置里面有个“禁用xposed”，是不是没有关闭。

**Comment by naloder** [comment]
@bluesky139 已经关闭正常了。。看后面一条回复
