### ISSUE TITLE
酷安隐藏底栏后有时候侧边栏会拉不出来，以及各种闪退问题。

### ISSUE THREAD

**Issue by Gokou-Ruri** [bluesky139/LTweaks#39]
底栏隐藏没问题，但侧边栏拉不出来。必须强行停止酷安，重新打开后才可能恢复正常。
概率性复现，大约20-30%触发率吧？

另外，启用l工具箱以后，有很多软件都会闪退，尤其是和webview或腾讯tbs有关系的软件。
例如王者荣耀助手，打开它不会闪退，浏览个人战绩也不会闪退，但点击首页里面的文章、视频页面，还没等界面切换进去就闪退了。（即在首页列表点击某个文章或视频的瞬间就闪退，必发性bug。）
这种页面本质上其实就是网页，但不清楚到底是Android webview还是腾讯tbs。

**Comment by bluesky139** [comment]
酷安的设置里面有个 "禁用 Xposed" 的功能，你看有没有关闭。

**Comment by bluesky139** [comment]
关于 webview，我之前遇到过，似乎是 Xposed 框架的问题，我在 XposedBridge 那边提过 issue，看这个 https://github.com/rovo89/XposedBridge/issues/221

当时我这边也是必定重现，是暂时性的想办法避免那样 hook，才没有了这个问题，看起来并不绝对。

**Comment by Gokou-Ruri** [comment]
@bluesky139 酷安早就没这项设置了，而且这项设置一直都是无效的。

**Comment by bluesky139** [comment]
酷安的这个设置生效时机并不是在最开始，所以对某些模块无效，请先关闭这个选项确认一下。

**Comment by Gokou-Ruri** [comment]
@bluesky139 所以说……酷安客户端早就没这一项设置了……怎么关？

**Comment by bluesky139** [comment]
设置 -> 帮助和反馈 -> 检测日志与测试 -> debug test.
