### ISSUE TITLE
“原生剪贴板在 Chrome 上的修复”应用支持问题

### ISSUE THREAD

**Issue by mikelei8291** [bluesky139/LTweaks#4]
这个修复并不能应用于 Chrome Beta，其他的版本比如 Dev 和 Canary 应该也不行
![image](https://user-images.githubusercontent.com/9620335/28491682-190d8092-6f28-11e7-94b1-74f740316fc9.png)

**Comment by bluesky139** [comment]
确实只能用于 chrome 稳定版，我下个版本把其它几个加上，它们代码是一样的理论上只需要把包名加进去就可以了。

**Comment by bluesky139** [comment]
Added in 439930ec46f54b214327de05b655f3ab06632965.
