### ISSUE TITLE
建议：增加将咸鱼分享强制改为系统分享的功能。

### ISSUE THREAD

**Issue by Gokou-Ruri** [bluesky139/LTweaks#40]
或者在它的分享菜单中增加一个“系统分享”的按钮。
另外，不希望分享内容里包含什么乱七八糟的文字，单纯的分享链接是坠吼的。
望考虑！

**Comment by Gokou-Ruri** [comment]
咸鱼菜单里那个“复制链接”复制出来的就是单纯的链接，没有乱七八糟的文字。

**Comment by bluesky139** [comment]
在 "系统/工具" 里面有个 "复制后分享" 的功能，你可以试试。

**Comment by Gokou-Ruri** [comment]
@bluesky139 没有这种需求，一天复制粘贴大约上百次，次次都弹分享框很烦人。

**Comment by bluesky139** [comment]
我也许可以考虑“复制后分享”这个功能指定应用，但没必要单独为某个应用做特定修改。
本身这个功能就是用来解决只能复制这种问题的。
或者有什么更好的方式来解决这一类问题。
对于复制频率不高的用户来讲现阶段的体验我觉得很好。

**Comment by bluesky139** [comment]
没有什么更好的解决方法，close.
