### ISSUE TITLE
在ASUS ZenUI (Android 6.0) 上所有功能无效

### ISSUE THREAD

**Issue by Gokou-Ruri** [bluesky139/LTweaks#41]
其它模块能正常工作，L工具箱完全无效。
![screenshot_20180429-190023](https://user-images.githubusercontent.com/26711804/39405838-a33faeae-4bdf-11e8-8387-4e18d9706146.png)
![screenshot_20180429-190014](https://user-images.githubusercontent.com/26711804/39405839-a3870164-4bdf-11e8-85c5-8e9d70094836.png)

**Comment by bluesky139** [comment]
没有在非标准 Android 上测试过，你可以重启一次手机，打开一些与你设置相关的应用，然后抓起 log 给我看看。
