### ISSUE TITLE
希望改进哔哩哔哩封面获取方法

### ISSUE THREAD

**Issue by huajideshutiao** [bluesky139/LTweaks#42]
可以改为在主页的卡片菜单里添加，也可以使用旧版方法，分享获取失效。

**Comment by bluesky139** [comment]
本来我是想用旧版方法的，毕竟用起来确实方便，只是哔哩哔哩改版后菜单不好加上去了。
我再继续尝试下好了。

**Comment by huajideshutiao** [comment]
又是可恶的改版…都不知道改成什么样了…

**Comment by bluesky139** [comment]
改回旧版方法了，https://github.com/bluesky139/LTweaks/commit/e6aaa334d041c7ade7e85e7c29f214c61fde80ab.
