### ISSUE TITLE
改进：最近任务右滑终止应用

### ISSUE THREAD

**Issue by aslarn** [bluesky139/LTweaks#43]
对我来说这个功能很好，但只支持aosp的最近任务，我在rr ROM中尝试了slim的最近任务，但它不能工作，希望能够增加支持。

**Comment by bluesky139** [comment]
任何第三方的最近任务都不支持，要支持 RR ROM 里面的 slim 实现起来应该没有问题，不过最近太忙此项目我都好久没更新过了，先 pending 起吧。

**Comment by aslarn** [comment]
谢谢

**Comment by bluesky139** [comment]
Added in https://github.com/bluesky139/LTweaks/commit/91c13f3cfd1d959ae1326a391588f0ae496ffec4.
