### ISSUE TITLE
关于哔哩哔哩版权番剧

### ISSUE THREAD

**Issue by ghost** [bluesky139/LTweaks#48]
能不能加一个破解版权下载的功能呢。。。

**Comment by Maolaohei** [comment]
哔哩布丁可以满足你

**Comment by ghost** [comment]
除了哔哩布丁，还有什么是可以破解版权下载的吗？

**Comment by Maolaohei** [comment]
以前是有其他大神开发的插件,就是因为部分人不满足,要求这要求那的,结果就黄了.
大神自己自用了,不分享了.

1535331149 <notifications@github.com> 于2018年7月5日周四 下午7:10写道：

**Comment by ghost** [comment]
好吧，我自己琢磨一下，实在找不到就网盘好了
谢谢大佬
