### ISSUE TITLE
Settings not exactly sticking at boot

### ISSUE THREAD

**Issue by Kalaris001** [bluesky139/LTweaks#52]
The "Hide share menu items" setting resets at boot. That is, all the menu items which I hide / disable come back after a reboot. However, when I enable and then disable even a single menu item which I had previously modified, all the disabled menu items disappear.

**Comment by bluesky139** [comment]
Which Android system are you using? I can't reproduce this problem on my side.
Can you take a reboot, share something once, then take log for me.

**Comment by Kalaris001** [comment]
On a Oneplus 5, Android 8.1, OOS 5.1.5.

To be clear, I should:

1. Reboot
2. Enable logging with, for example, Logcat Reader
3. Share an item with any application in the share menu
4. Send you the log. 

Kindly correct me if I'm wrong.

**Comment by bluesky139** [comment]
Yes, that's right.

**Comment by Kalaris001** [comment]
[L Tweaks.txt](https://github.com/bluesky139/LTweaks/files/2336541/L.Tweaks.txt)

Log attached.

**Comment by bluesky139** [comment]
I can't find any useful info from log, but I guess it's the problem that settings can't be read due to permission or something.

Is there any other settings not take effect after reboot?

**Comment by Kalaris001** [comment]
I actually uninstalled the module. Two many apps were force-closing and
Google Maps' location sharing was acting wonky.

But thank you so much for taking the time.

Peace.
