### ISSUE TITLE
求更新…

### ISSUE THREAD

**Issue by fanghuan27** [bluesky139/LTweaks#53]
youtube 相册 google搜索…G+

**Comment by bluesky139** [comment]
Google 搜索更新: 8c5e1a773addb6cf48e8c9beeeb8b3f315171c36
G+ 更新: 89f5ec49add9ddee7c60ca58de270a060c9872c9
相册更新: 1dc4efbc38d14d9ee51d3265bff2ae7370df1628.
Youtube 没有发现什么问题.

**Comment by fanghuan27** [comment]
感谢作者 想问下youtube现在支持到哪个版本？之前更新1.20我是换到13.23.59去底栏是好的  这个版本后边更新了好多版本啦不适配一个么

**Comment by bluesky139** [comment]
Youtube 从 13.23.59 更新适配后到现在最新的 13.42.52 都是兼容的，至少我正在用的 13.42.52 是正常的，期间我也更新过很多次都没有问题。

**Comment by fanghuan27** [comment]
我试了卸载了youtube adaway后好了 看来是这东西不兼容了
