### ISSUE TITLE
嗶哩嗶哩完美夜間模式會導致關注和粉絲列表出現黑底黑字情況

### ISSUE THREAD

**Issue by i9602097** [bluesky139/LTweaks#54]
![screenshot_20181029-122822](https://user-images.githubusercontent.com/18757629/47629529-96f40b00-db76-11e8-9e79-81b1441d525f.png)
如圖，求修正

**Comment by bluesky139** [comment]
这个页面是一个网页，是我把所有网页背景全设为黑色所致，然而我发现这一操作也导致其它地方也容易出现问题，所以前几天我已经去掉了这一修改 addff58946ae5c269da156b05fc35d6677bf28fe 。

我觉得你可以向 bilibili 官方报告这个页面在夜间模式下仍为白色背景的问题，我这边并不好做处理。

**Comment by i9602097** [comment]
其實我不介意原版還是白底的問題
反而黑底黑字就真受不了
改回來就可以了
希望能快點推送去Google Play
我是使用Google Play版本的而現在的版本還未修正這問題
