### ISSUE TITLE
建议加入插入usb锁定状态为mtp

### ISSUE THREAD

**Issue by daiaji** [bluesky139/LTweaks#56]
https://forum.xda-developers.com/xposed/modules/mod-usb-marshmallow-1-0-t3272072
这个模块太老了8.0用不了
求集成到l工具箱（然后我发现重力工具箱居然没这功能 很神奇）

**Comment by bluesky139** [comment]
我记得有个 property 是可以直接修改的，你可以试下 `setprop persist.sys.usb.config mtp`，或者查查 `persist.sys.usb.config` 有什么相关的东西。

**Comment by daiaji** [comment]
@bluesky139 `su`之后`setprop persist.sys.usb.config mtp`没效果重启还是充电状态
https://blog.csdn.net/subingxi/article/details/80424893
这有篇文章
但是我估摸着 到O之后怕是又改了
https://blog.csdn.net/u012846789/article/details/73195335
看起来有个传言就是7.1时这个东西被认为是BUG 修了
之后8.0又加上了（我又改了回去.jpg）
https://blog.csdn.net/u013894427/article/details/79485179
而且8.0似乎不开MTP没法用adb调试……
很怪啊
`setprop persist.sys.usb.config mtp`好像会导致adb重启后关掉

**Comment by bluesky139** [comment]
`setprop persist.sys.usb.config mtp` 是会导致 adb 关掉，你可以加上 adb，像这样 `setprop persist.sys.usb.config adb,mtp`.

另外，开发者选项里有相关设置你有没有试过。

**Comment by daiaji** [comment]
@bluesky139  开发者选项里那个调到mtp 拔掉usb再插还是会再充电 都没啥用

**Comment by bluesky139** [comment]
估计确实需要改系统才行，这个功能不太好测试，因为模拟器里面无法测试。
我先去准备个测试机。

**Comment by daiaji** [comment]
@bluesky139 ？ 你现在在用牛轧糖还是水果吗？
moto z2 force洋垃圾好价 严重烧屏机才400

**Comment by bluesky139** [comment]
我用的是 8.1 的系统，但是我不能拿我的主力机来测试。之前拿来调试，结果搞来系统起不起来。

我手上还有一台以前的 Nexus 5，后面先刷机再测试。

**Comment by daiaji** [comment]
@bluesky139 讲道理还是f2fs太菜了 没有透明压缩还没快照 有快照搞机方便不是一点半点
btrfs性能又太菜了 
老实说a/b方案也很菜 为了无缝更新 搞双系统
怕不是嫌你64g用不完 防翻车 无缝更新 linux下方案甚至不止一套
实在算不上明智
而且在linux下热更新不是常识吗？

**Comment by daiaji** [comment]
@bluesky139 
https://github.com/CzBiX/wifi-password-android
反正有源码也整合一下这个小功能？
![screenshot_20181201-203255](https://user-images.githubusercontent.com/25875791/49328276-94873580-f5a8-11e8-93c4-4b9faee43fb5.png)
直接在这里显示密码

**Comment by bluesky139** [comment]
我觉得这种做法不好，不进行整合，你可以直接用那个模块。

**Comment by daiaji** [comment]
@bluesky139 主要是怕不知道哪天这模块也和mod-usb-marshmallow一样不知道哪天就die了
没人管了
wifi-password-android只是刚好 8.0 API没变化 界面也没变化
wifi-password-android毕竟最后一次更新代码是八个月前 声明的也是只支持到牛轧糖……

**Comment by bluesky139** [comment]
通常这些小模块都是因为个人喜好才出现的，我的这个也是，所以不会花大量时间在上面，更不可能实现所有人的需求，这都是空闲时间在维护，我曾经也有段时间完全没有更新过。

如果那个项目还能用，那就继续用，到不能用的时候再多。

如果你也有开发能力，加入进来是最好的，fork 他的项目进行修改。

**Comment by bluesky139** [comment]
Added in 357f8ff623c94496a30d534b28cf7337e362db92.

**Comment by daiaji** [comment]
@bluesky139 没编译发布吗？

**Comment by bluesky139** [comment]
v1.22.0 已发布.
