### ISSUE TITLE
LiveDisplay 时间修改功能无效

### ISSUE THREAD

**Issue by Undefined-User** [bluesky139/LTweaks#58]
rt，系统是RR6.2.1(Android8.1)，之前修改成功过，似乎是更新1.21后失效的，模块正常工作(因为修改play和chrome等功能没有问题)

**Comment by Undefined-User** [comment]
https://github.com/bluesky139/LTweaks/blob/master/app/src/main/java/li/lingfeng/ltweaks/xposed/system/XposedLightAmberInDaylight.java#L38
@bluesky139 帮你找好bug位置了，大于等于号写成小于等于号了......

**Comment by bluesky139** [comment]
你是在说修改 Live Display 的日出日落时间问题，但为啥引用了另一个功能 "Light amber in daylight" 的文件？

Live Display 的时间修改是在 [https://github.com/bluesky139/LTweaks/blob/master/app/src/main/java/li/lingfeng/ltweaks/xposed/system/XposedLiveDisplayTwilight.java](https://github.com/bluesky139/LTweaks/blob/master/app/src/main/java/li/lingfeng/ltweaks/xposed/system/XposedLiveDisplayTwilight.java)，这个功能在做好之后就再也没动过了。

**Comment by Undefined-User** [comment]
抱歉并没有打包测试过，以为上个版本能用所以直接去翻commit了(翻车了233
发之后退回上个版本试了下发现也不能用orz，应该是记错了
是RR系统的自身原因导致的嘛？

**Comment by bluesky139** [comment]
有可能 RR ROM 更新过，你更新过系统？
