### ISSUE TITLE
1.21.0 的历史价格在8.0会报错

### ISSUE THREAD

**Issue by remewb** [bluesky139/LTweaks#59]
RT 无法正常运行

**Comment by bluesky139** [comment]
请抓下 log, 我现在在 8.1 的系统上没有问题。

**Comment by remewb** [comment]
[error.log](https://github.com/bluesky139/LTweaks/files/2683669/error.log)

**Comment by bluesky139** [comment]
报错具体报什么错？
从 log 的情况来看，剪贴板已经复制到分享链接，弹出了分享按钮，但你似乎并没有点分享到历史价格？

**Comment by remewb** [comment]
点了历史价格 直接崩溃无法运行，我也不知道日志里为什么没有记录 1.20的时候还是正常的

**Comment by bluesky139** [comment]
能在电脑上抓下 log 么，完整 log 可以看到更多信息。

**Comment by remewb** [comment]
[log.txt](https://github.com/bluesky139/LTweaks/files/2692035/log.txt)

**Comment by bluesky139** [comment]
Fixed via 228814ae260205e6616ed51ab26f7d25b4d4f988.
感谢提供 log.
