### ISSUE TITLE
Go to App Ops (LOS) 

### ISSUE THREAD

**Issue by oroboros** [bluesky139/LTweaks#60]
I'm expecting to see a link or something from the app info screen, but not sure exactly where to look. Am on LOS 15.1

**Comment by bluesky139** [comment]
This menu item should be added into top right 3 dot menu, it's not there?

**Comment by oroboros** [comment]
> This menu item should be added into top right 3 dot menu, it's not there?

Not on my system.

**Comment by oroboros** [comment]
Perhaps you can launch the relative app ops page from the version number or something. Might also be nice to add 'freeze/defrost', and something like tapping the icon launches the app.

**Comment by oroboros** [comment]
After reboot I see it... Thanks!
