### ISSUE TITLE
App info : suggestions (add freeze, launch app) 

### ISSUE THREAD

**Issue by oroboros** [bluesky139/LTweaks#61]
Perhaps you can launch the relative app ops page from the version number rather than from menu. 

Might also be nice to add 'freeze/defrost', and something like tapping the icon launches the app.

**Comment by bluesky139** [comment]
Not only ops menu is there, there are other menus, so they can be launched in same place.

I considered "freeze/defrost" before, but now, I don't want to implement it anymore, the management for apps on new Android system is more and more better.
