### ISSUE TITLE
安卓4.4不再被支持了吗？

### ISSUE THREAD

**Issue by zaoqi-unsafe** [bluesky139/LTweaks#63]

**Comment by bluesky139** [comment]
不再支持，4.4 已经是相当老的版本了。

**Comment by zaoqi-unsafe** [comment]
很多非手机设备永远的停留在4.4

**Comment by zaoqi-unsafe** [comment]
有某些电子墨水屏设备，某些廉价安卓智能手表，某个电子词典等

**Comment by bluesky139** [comment]
系统不停更新，我不可能一直去支持老系统，5.0/6.0 也在考虑后面逐步停止支持。

这不是一个有大量用户使用的项目，因此我没必要在低系统上纠结。

如果你始终坚持旧系统，你可以尝试以前发布过的老版本。

**Comment by zaoqi-unsafe** [comment]
我没有坚持旧系统。
我会暂时使用老版本，之后用自己写的操作系统和编程语言和非编程语言。
