### ISSUE TITLE
总是启用MTP还是有问题

### ISSUE THREAD

**Issue by daiaji** [bluesky139/LTweaks#64]
![image](https://user-images.githubusercontent.com/25875791/50587897-ab2bef80-0eba-11e9-866f-10864eac5ec4.png)

比如这样
默认的“为此设备充电”开起了MTP但是没有可以访问的储存设备
手动切到“传输文件”还是可以用的

**Comment by bluesky139** [comment]
我做了点小修补，但没法测试，请试试是否有效。

[MTP-Always.zip](https://github.com/bluesky139/LTweaks/files/2744685/MTP-Always.zip)

**Comment by daiaji** [comment]
@bluesky139 发布试试？🙄我试着好像OK

**Comment by bluesky139** [comment]
发布暂缓，后面什么时候再发布。

Change is e24e0f2beb2839b044d96326bc0fcd6ec2cd79a0.
